Predict the market price of a house automatically using linear regression model

In [1]:
import pandas as pd  
import seaborn as sns

In [82]:
data=pd.read_csv("HousePricePrediction.csv")
data.head()

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,0,60,RL,8450,Inside,1Fam,5,2003,2003,VinylSd,0,856,208500
1,1,20,RL,9600,FR2,1Fam,8,1976,1976,MetalSd,0,1262,181500
2,2,60,RL,11250,Inside,1Fam,5,2001,2002,VinylSd,0,920,223500
3,3,70,RL,9550,Corner,1Fam,5,1915,1970,Wd Sdng,0,756,140000
4,4,60,RL,14260,FR2,1Fam,5,2000,2000,VinylSd,0,1145,250000

In [83]:
data["MSZoning"].unique()

<StringArray>
['RL', 'RM', 'C (all)', 'FV', 'RH']
Length: 5, dtype: str

In [84]:
data["LotConfig"].unique()

<StringArray>
['Inside', 'FR2', 'Corner', 'CulDSac', 'FR3']
Length: 5, dtype: str

In [85]:
data["BldgType"].unique()

<StringArray>
['1Fam', '2fmCon', 'Duplex', 'TwnhsE', 'Twnhs']
Length: 5, dtype: str

In [86]:
data["Exterior1st"].unique()

<StringArray>
['VinylSd', 'MetalSd', 'Wd Sdng', 'HdBoard', 'BrkFace', 'WdShing', 'CemntBd',
 'Plywood', 'AsbShng',  'Stucco', 'BrkComm', 'AsphShn',   'Stone', 'ImStucc',
  'CBlock']
Length: 15, dtype: str

In [87]:
data=pd.get_dummies(data,columns=["MSZoning","LotConfig","BldgType","Exterior1st"],drop_first=True,dtype=int)
data.head()

,Id,MSSubClass,LotArea,OverallCond,YearBuilt,YearRemodAdd,BsmtFinSF2,TotalBsmtSF,SalePrice,MSZoning_FV,...,Exterior1st_CemntBd,Exterior1st_HdBoard,Exterior1st_ImStucc,Exterior1st_MetalSd,Exterior1st_Plywood,Exterior1st_Stone,Exterior1st_Stucco,Exterior1st_VinylSd,Exterior1st_Wd Sdng,Exterior1st_WdShing
0,0,60,8450,5,2003,2003,0,856,208500,0,...,0,0,0,0,0,0,0,1,0,0
1,1,20,9600,8,1976,1976,0,1262,181500,0,...,0,0,0,1,0,0,0,0,0,0
2,2,60,11250,5,2001,2002,0,920,223500,0,...,0,0,0,0,0,0,0,1,0,0
3,3,70,9550,5,1915,1970,0,756,140000,0,...,0,0,0,0,0,0,0,0,1,0
4,4,60,14260,5,2000,2000,0,1145,250000,0,...,0,0,0,0,0,0,0,1,0,0

In [88]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 35 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Id                   1460 non-null   int64
 1   MSSubClass           1460 non-null   int64
 2   LotArea              1460 non-null   int64
 3   OverallCond          1460 non-null   int64
 4   YearBuilt            1460 non-null   int64
 5   YearRemodAdd         1460 non-null   int64
 6   BsmtFinSF2           1460 non-null   int64
 7   TotalBsmtSF          1460 non-null   int64
 8   SalePrice            1460 non-null   int64
 9   MSZoning_FV          1460 non-null   int64
 10  MSZoning_RH          1460 non-null   int64
 11  MSZoning_RL          1460 non-null   int64
 12  MSZoning_RM          1460 non-null   int64
 13  LotConfig_CulDSac    1460 non-null   int64
 14  LotConfig_FR2        1460 non-null   int64
 15  LotConfig_FR3        1460 non-null   int64
 16  LotConfig_Inside     1460 non-null   int64
 17  BldgType_2fmCon      1460 non-null   int64
 18  BldgType_Duplex      1460 non-null   int64
 19  BldgType_Twnhs       1460 non-null   int64
 20  BldgType_TwnhsE      1460 non-null   int64
 21  Exterior1st_AsphShn  1460 non-null   int64
 22  Exterior1st_BrkComm  1460 non-null   int64
 23  Exterior1st_BrkFace  1460 non-null   int64
 24  Exterior1st_CBlock   1460 non-null   int64
 25  Exterior1st_CemntBd  1460 non-null   int64
 26  Exterior1st_HdBoard  1460 non-null   int64
 27  Exterior1st_ImStucc  1460 non-null   int64
 28  Exterior1st_MetalSd  1460 non-null   int64
 29  Exterior1st_Plywood  1460 non-null   int64
 30  Exterior1st_Stone    1460 non-null   int64
 31  Exterior1st_Stucco   1460 non-null   int64
 32  Exterior1st_VinylSd  1460 non-null   int64
 33  Exterior1st_Wd Sdng  1460 non-null   int64
 34  Exterior1st_WdShing  1460 non-null   int64
dtypes: int64(35)
memory usage: 399.3 KB

In [ ]:
# Id column is not usefull

x=data.drop(columns=["SalePrice","Id"]) 

y=data["SalePrice"]
y.info()

<class 'pandas.Series'>
RangeIndex: 1460 entries, 0 to 1459
Series name: SalePrice
Non-Null Count  Dtype
--------------  -----
1460 non-null   int64
dtypes: int64(1)
memory usage: 11.5 KB

In [90]:
x.info()

<class 'pandas.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 33 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   MSSubClass           1460 non-null   int64
 1   LotArea              1460 non-null   int64
 2   OverallCond          1460 non-null   int64
 3   YearBuilt            1460 non-null   int64
 4   YearRemodAdd         1460 non-null   int64
 5   BsmtFinSF2           1460 non-null   int64
 6   TotalBsmtSF          1460 non-null   int64
 7   MSZoning_FV          1460 non-null   int64
 8   MSZoning_RH          1460 non-null   int64
 9   MSZoning_RL          1460 non-null   int64
 10  MSZoning_RM          1460 non-null   int64
 11  LotConfig_CulDSac    1460 non-null   int64
 12  LotConfig_FR2        1460 non-null   int64
 13  LotConfig_FR3        1460 non-null   int64
 14  LotConfig_Inside     1460 non-null   int64
 15  BldgType_2fmCon      1460 non-null   int64
 16  BldgType_Duplex      1460 non-null   int64
 17  BldgType_Twnhs       1460 non-null   int64
 18  BldgType_TwnhsE      1460 non-null   int64
 19  Exterior1st_AsphShn  1460 non-null   int64
 20  Exterior1st_BrkComm  1460 non-null   int64
 21  Exterior1st_BrkFace  1460 non-null   int64
 22  Exterior1st_CBlock   1460 non-null   int64
 23  Exterior1st_CemntBd  1460 non-null   int64
 24  Exterior1st_HdBoard  1460 non-null   int64
 25  Exterior1st_ImStucc  1460 non-null   int64
 26  Exterior1st_MetalSd  1460 non-null   int64
 27  Exterior1st_Plywood  1460 non-null   int64
 28  Exterior1st_Stone    1460 non-null   int64
 29  Exterior1st_Stucco   1460 non-null   int64
 30  Exterior1st_VinylSd  1460 non-null   int64
 31  Exterior1st_Wd Sdng  1460 non-null   int64
 32  Exterior1st_WdShing  1460 non-null   int64
dtypes: int64(33)
memory usage: 376.5 KB

In [91]:
#split training and testing data
from sklearn.model_selection import train_test_split

In [92]:
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42)

In [93]:
x_test.shape

(292, 33)

In [94]:
x_train.shape

(1168, 33)

In [95]:
#linear regreesion model training
from sklearn.linear_model import LinearRegression

In [96]:
reg = LinearRegression().fit(x_train, y_train)

In [97]:
y_pred = reg.predict(x_test)

In [98]:
from sklearn.metrics import r2_score

In [99]:
r2_score(y_test, y_pred)

0.6195131796544862

In [100]:
y_pred_train = reg.predict(x_train)

In [101]:
r2_score(y_train, y_pred_train)

0.6142291549169858